version: "3.9"

services:
  mms_database:
    container_name: mms_database
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/initialize:/docker-entrypoint-initdb.d
    networks:
      - mms_database-network

networks:
  mms_database-network:
    driver: bridge
